Moved duplicate code to BuildingBlocks shared lib
nmshd/backbone pull request #109
Opened 2023-05-03 14:11 UTC by Dannyps

# Readiness checklist

- [ ] I added/updated unit tests.
- [ ] I added/updated integration tests.
- [x] I ensured that the PR title is good enough for the changelog.
- [x] I labeled the PR.

2023-05-03 14:12 UTC, Dannyps commented
@tnotheis I've opening with PR with just a small change so that you confirm if this is the desired approach. Thanks

2023-05-04 05:31 UTC, tnotheis reviewed
Almost. But don't move the stuff to BuildingBlocks.Application. The Application projects should not know anything about the "outside world", like the database, the blob storage, the event bus - and not about the HTTP API either.

2023-05-05 05:15 UTC, tnotheis commented on BuildingBlocks/src/BuildingBlocks.Application/BuildingBlocks.Application.csproj
> +		<PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.Abstractions" Version="6.0.2" />
Remember to remove the added references here

2023-05-08 07:37 UTC, tnotheis requested changes

2023-05-08 07:37 UTC, tnotheis commented on BuildingBlocks/src/BuildingBlocks.API/Mvc/JsonConverters/UtcDateTimeConverter.cs
> +    }
```suggestion
    public UtcDateTimeConverter() : base(DEFAULT_FORMAT) { }
```

2023-05-08 07:37 UTC, tnotheis commented on BuildingBlocks/src/BuildingBlocks.API/Mvc/JsonConverters/UtcDateTimeConverter.cs
> +    }
```suggestion
    public NullableUtcDateTimeConverter() : base(UtcDateTimeConverter.DEFAULT_FORMAT) { }
```

2023-05-08 09:10 UTC, tnotheis approved these changes

2023-05-08 09:12 UTC, merged