Repositories for Relationships module
nmshd/backbone pull request #121
Opened 2023-05-09 08:21 UTC by JLSRKonk

# Readiness checklist

- [ ] I added/updated unit tests.
- [ ] I added/updated integration tests.
- [x] I ensured that the PR title is good enough for the changelog.
- [x] I labeled the PR.

2023-05-10 08:04 UTC, tnotheis requested changes

2023-05-10 08:04 UTC, tnotheis commented on Modules/Relationships/src/Relationships.Infrastructure/Persistence/Database/Repository/RelationshipsRepository.cs
> +        await Task.WhenAll(changes.ItemsOnPage.Select(FillContentOfChange).ToArray());
You forgot to use FillContentOfChanges

2023-05-10 08:04 UTC, tnotheis commented on Modules/Relationships/src/Relationships.Infrastructure/Persistence/Database/Repository/RelationshipsRepository.cs
> +        await Task.WhenAll(relationships.ItemsOnPage.SelectMany(r => r.Changes).Select(FillContentOfChange).ToArray());
You forgot to use FillContentOfChanges

2023-05-10 08:51 UTC, JLSRKonk commented on Modules/Relationships/src/Relationships.Application/Infrastructure/Persistence/Repository/IRelationshipsRepository.cs
> +    Task<Relationship> FindRelationshipPlain(RelationshipId id, CancellationToken cancellationToken);
The Messages repository used to have a method like this, it returns the requested Relationship without any constraints (in this case, it doesn't require a specific participant).
Should I rename the FindRelationship methods to something like this?

FindRelationship -> FindRelationshipWithParticipant
FindRelationshipPlain -> FindRelationship

2023-05-10 10:54 UTC, tnotheis commented
You don’t need the Plain method. Use the other one. It’s better to check for the participant anyway.

Timo Notheisen
Senior Developer
+49 (6221) 4312127
***@***.***
j&s-soft GmbH
Max-Jarecki-Straße 21
69115Heidelberg
Germany
js-soft.com
Sitz der Gesellschaft/Registered Office: 
​Max-Jarecki-Straße 21, D-69115 Heidelberg
 Geschäftsführer: Dirk Jennerjahn
 Handelsregister Amtsgericht Mannheim HRB 337601

​​Diese E-Mail kann Betriebs- oder Geschäftsgeheimnisse oder sonstige vertrauliche Informationen enthalten. Sollten Sie diese E-Mail irrtümlich erhalten haben, ist Ihnen eine Kenntnisnahme des Inhalts, eine Vervielfältigung oder Weitergabe der E-Mail ausdrücklich untersagt. Bitte benachrichtigen Sie uns und vernichten Sie die empfangene E-Mail. Vielen Dank.
 
 This e-mail may contain trade secrets or privileged, undisclosed, or otherwise confidential information. If you have received this e-mail in error, you are hereby notified that any review, copying, or distribution of it is strictly prohibited. Please inform us immediately and destroy the original transmittal. Thank you for your cooperation.

2023-05-10 10:56 UTC, tnotheis commented on Modules/Relationships/src/Relationships.Application/Infrastructure/Persistence/Repository/IRelationshipsRepository.cs
> +    Task<Relationship> FindRelationshipPlain(RelationshipId id, CancellationToken cancellationToken);
You don’t need the Plain method. Use the other one. It’s better to check for the participant anyway.

2023-05-10 13:47 UTC, tnotheis requested changes

2023-05-10 13:47 UTC, tnotheis commented on Modules/Relationships/src/Relationships.Application/Infrastructure/Persistence/Repository/IRelationshipsRepository.cs
> +    Task<int> CountNumberOfRelationshipsOfTemplate(RelationshipTemplateId relationshipTemplateId, CancellationToken cancellationToken);
Can be removed. It's unused

2023-05-11 05:38 UTC, tnotheis approved these changes

2023-05-11 05:38 UTC, tnotheis approved these changes

2023-05-11 10:08 UTC, merged