Added "Data" property to HttpError
nmshd/backbone pull request #136
Opened 2023-05-18 15:53 UTC by filipemmagalhaes

# Readiness checklist

- [ ] I added/updated unit tests.
- [ ] I added/updated integration tests.
- [x] I ensured that the PR title is good enough for the changelog.
- [x] I labeled the PR.

2023-05-22 06:37 UTC, tnotheis requested changes

2023-05-22 06:37 UTC, tnotheis commented on Admin.API/Extensions/IServiceCollectionExtensions.cs
> +                            ""));
Remove the default value. An empty string doesn't make any sense.

2023-05-22 06:37 UTC, tnotheis commented on Admin.API/HttpError.cs
Can you remove these classes please? And if there are any errors, use the ones from BuildingBlocks.API. Daniel seems to have missed this file during his refactorings.

2023-05-22 06:37 UTC, tnotheis commented on BuildingBlocks/src/BuildingBlocks.API/Mvc/ExceptionFilters/CustomExceptionFilter.cs
Remove all the default values for data.

2023-05-22 06:37 UTC, tnotheis commented on ConsumerApi/Extensions/IServiceCollectionExtensions.cs
> +                            ""));
Remove the default value

2023-05-23 05:14 UTC, tnotheis requested changes

2023-05-23 05:14 UTC, tnotheis commented on Admin.API/HttpResponseEnvelope.cs
Is this class the same as the corresponding one in BuildingBlocks.API? If so, you can remove this one as well.

@Dannyps Is there a special reason you didn't delete this class or did you simply forget it?

2023-05-23 05:16 UTC, tnotheis commented on Admin.API/Extensions/IServiceCollectionExtensions.cs
> +                            ""));
Now you changed the parameter, instead of removing it...

2023-05-23 05:16 UTC, tnotheis commented on BuildingBlocks/src/BuildingBlocks.API/Mvc/ExceptionFilters/CustomExceptionFilter.cs
Now you changed the parameter, instead of removing it...

2023-05-23 05:16 UTC, tnotheis commented on ConsumerApi/Extensions/IServiceCollectionExtensions.cs
> +                            ""));
Now you changed the parameter, instead of removing it...

2023-05-23 08:31 UTC, filipemmagalhaes commented on Admin.API/HttpResponseEnvelope.cs
Code removed

2023-05-23 08:58 UTC, tnotheis requested changes

2023-05-23 08:58 UTC, tnotheis commented on Admin.API/Extensions/IServiceCollectionExtensions.cs
> +                            ""));// TODO: add docs
space between `;` and `//` is missing

2023-05-23 08:58 UTC, tnotheis commented on BuildingBlocks/src/BuildingBlocks.API/Mvc/ExceptionFilters/CustomExceptionFilter.cs
> +            "" // TODO: add documentation link
Lots of unnecessary spaces

2023-05-23 08:58 UTC, tnotheis commented on BuildingBlocks/src/BuildingBlocks.API/Mvc/ExceptionFilters/CustomExceptionFilter.cs
> +                "",// TODO: add documentation link
space between `;` and `//` is missing

2023-05-23 08:58 UTC, tnotheis commented on ConsumerApi/Extensions/IServiceCollectionExtensions.cs
> +                            null));
There is still a `null`

2023-05-23 11:22 UTC, tnotheis approved these changes

2023-05-23 11:24 UTC, merged