Admin UI Identity Quotas
nmshd/backbone pull request #183
Opened 2023-06-27 12:27 UTC by JLSRKonk

# Readiness checklist

- [ ] I added/updated unit tests.
- [ ] I added/updated integration tests.
- [x] I ensured that the PR title is good enough for the changelog.
- [x] I labeled the PR.

2023-06-27 12:31 UTC, JLSRKonk commented
Screenshots:
![identity](https://github.com/nmshd/backbone/assets/118175875/37ae7e50-d1fc-439d-8eda-a2aeeb344d04)

![identity-quota](https://github.com/nmshd/backbone/assets/118175875/ebd19c13-5549-4c41-97d1-036c00fb4f58)

2023-06-28 07:30 UTC, tnotheis requested changes
I would suggest getting rid of the "DTO" postfix. The Backbone only needs it to distinguish it from the domain classes.

2023-06-28 08:33 UTC, JLSRKonk commented on AdminUI/src/app/services/quotas-service/quotas.service.ts
> +export interface IdentityQuotaDefinitionDTO {
We don't have quotas for Identities in the main branch, as far as I am aware. I got this DTO from the open pull request "Quotas For Identities: application #175". We have a DTO definition with this name there. https://github.com/nmshd/backbone/pull/175/files#diff-8a89fce308c5fb982cdce41f36360db55512b5237a4eceaaa83ced4dae39a205

2023-06-28 09:35 UTC, JLSRKonk commented on AdminUI/src/app/components/quotas/identity/identity-edit/identity-edit.component.html
> +                        dateConvert(identity.createdAt)
When we use a date variable like this, without any kind of processing, the full date date string will be displayed. I can see two ways to solve this.

1. Use angular DatePipes. In this scenario, we would use the DatePipe like this `{{ identity.createdAt | date }}` and the date would be properly displayed. We can customize the way the DatePipe displays dates globally.
Here is the documentation: https://angular.io/api/common/DatePipe , https://angular.io/api/common/DATE_PIPE_DEFAULT_OPTIONS

2. Alternatively, we can manipulate the date in the data model, to change its type, and display it directly.

2023-06-28 11:49 UTC, tnotheis commented on AdminUI/src/app/components/quotas/identity/identity-edit/identity-edit.component.html
> +                        dateConvert(identity.createdAt)
The latter is the solution I would have chosen for an MVVM application. But I don't know how to do the MVC way.

2023-06-28 11:52 UTC, tnotheis commented on AdminUI/src/app/services/quotas-service/quotas.service.ts
> +export interface IdentityQuotaDefinitionDTO {
Ohh, okay, then it is incorrect there as well. :) It should be called IdentityQuotaDTO - or, if we get rid of the DTO prefix - just IdentityQuota.

2023-06-29 08:06 UTC, tnotheis requested changes

2023-06-29 08:06 UTC, tnotheis commented on AdminUI/src/app/app.module.ts
> +            useValue: { dateFormat: 'd/M/yyyy' },
As the majority of the users will probably be German, can you use `dd.mm.yyyy` as the date format please? Plus: the time would be helpful as well, so you should change it to `dd.mm.yyyy HH:mm:ss`

2023-06-29 09:40 UTC, tnotheis approved these changes

2023-06-29 09:41 UTC, tnotheis requested changes
Wait

2023-06-29 09:41 UTC, tnotheis commented
Don't merge this to main. It should go into the feature branch for identity quota

2023-06-29 11:50 UTC, tnotheis approved these changes

2023-06-29 12:28 UTC, merged