Creation of OAuth clients
nmshd/backbone pull request #185
Opened 2023-06-30 18:05 UTC by daniel-almeida-konkconsulting

# Readiness checklist

- [ ] I added/updated unit tests.
- [ ] I added/updated integration tests.
- [X] I ensured that the PR title is good enough for the changelog.
- [X] I labeled the PR.

2023-06-30 18:07 UTC, daniel-almeida-konkconsulting commented
![image](https://github.com/nmshd/backbone/assets/115644988/6abd4270-7e52-4e9a-92ee-c6c276ec2e41)

2023-06-30 18:08 UTC, daniel-almeida-konkconsulting commented
![image](https://github.com/nmshd/backbone/assets/115644988/1435c6a6-4eb4-47f6-aa0f-06aff0a28c61)

2023-06-30 18:08 UTC, daniel-almeida-konkconsulting commented
![image](https://github.com/nmshd/backbone/assets/115644988/a91d070c-297a-474b-90f4-00343c3f969b)

2023-06-30 19:30 UTC, tnotheis commented
There are a lot of conflicts

2023-07-03 05:30 UTC, tnotheis commented on Modules/Devices/src/Devices.Application/ApplicationErrors.cs
> +            return new ApplicationError("error.platform.validation.device.clientAlreadyExists", "The client already exists. Try a different client");
```suggestion
            return new ApplicationError("error.platform.validation.device.clientAlreadyExists", "A client with the given client id already exists. Try a different client id");
```

2023-07-03 05:30 UTC, tnotheis commented on Modules/Devices/src/Devices.Application/Clients/Commands/CreateClients/Handler.cs
> +            && await _oAuthClientsRepository.Find(request.ClientId, cancellationToken) != null)
I would extract the second condition into a variable or method to make it more readable.

2023-07-03 05:31 UTC, tnotheis commented on Modules/Devices/src/Devices.Application/Clients/Commands/CreateClients/Handler.cs
> +            && await _oAuthClientsRepository.Find(request.ClientId, cancellationToken) != null)
I would extract the second condition into a variable or method to make it more readable.

2023-07-03 06:38 UTC, tnotheis requested changes

2023-07-03 06:38 UTC, tnotheis commented on Modules/Devices/src/Devices.Application/Clients/Commands/CreateClients/Handler.cs
> +            && await _oAuthClientsRepository.Find(request.ClientId, cancellationToken) != null)
Why do you read the client if you just use it to check for null? Instead, you could have an "Exists" method on the repository.

2023-07-03 06:38 UTC, tnotheis commented on AdminApi/Controllers/ClientsController.cs
> +    [ProducesResponseType(StatusCodes.Status404NotFound)]
In which case does this produce a 404?

2023-07-03 06:38 UTC, tnotheis commented on Modules/Devices/src/Devices.Application/ClientIdGenerator.cs
> +public class ClientIdGenerator
This class only contains static members, so you can as well make it static.

2023-07-03 06:38 UTC, tnotheis commented on Modules/Devices/src/Devices.Application/Password.cs
> +public static class Password
Call it PasswordGenerator to match `ClientIdGenerator`

2023-07-03 06:38 UTC, tnotheis commented on Modules/Devices/src/Devices.Infrastructure/Persistence/Repository/OAuthClientsRepository.cs
> +            throw new Exception($"Failed to create the client: '{displayName}'");
Add the client id to the exception, so that we can comprehend the error from the logs.

2023-07-03 06:38 UTC, tnotheis commented on Modules/Devices/src/Devices.Infrastructure/Persistence/Repository/OAuthClientsRepository.cs
> +        var managerResult = await _applicationManager.CreateAsync(new OpenIddictApplicationDescriptor
The result is actually a client, so you should call it like that (=> `client`). 

I have no idea why it was called managerResult. Doesn't sound like a name I would come up with. So it probably was the person who made the OpenIddict change.

2023-07-03 10:53 UTC, tnotheis requested changes

2023-07-03 10:53 UTC, tnotheis commented on Modules/Devices/src/Devices.Application/Clients/Commands/CreateClients/Handler.cs
> +                throw new OperationFailedException(ApplicationErrors.Devices.ClientAlreadyExists());
```suggestion
                throw new OperationFailedException(ApplicationErrors.Devices.ClientIdAlreadyExists());
```

2023-07-03 14:50 UTC, tnotheis approved these changes

2023-07-04 07:18 UTC, tnotheis approved these changes

2023-07-04 07:19 UTC, merged