Integration tests not running on Pipeline
nmshd/backbone pull request #216
Opened 2023-07-17 14:29 UTC by Dannyps

# Readiness checklist

- [ ] I added/updated unit tests.
- [] I added/updated integration tests.
- [x] I ensured that the PR title is good enough for the changelog.
- [x] I labeled the PR.

2023-07-17 14:30 UTC, Dannyps commented
We were skipping the building of the tests, which resulted in them not being ran.

2023-07-17 14:31 UTC, tnotheis requested changes

2023-07-17 14:31 UTC, tnotheis commented on .ci/integration-test.ts
> +await $`dotnet test "Backbone.sln" --filter "Category=Integration&TestCategory!~ignore"`;
Run separate `dotnet restore` and `dotnet build` commands. This will make the output easier to read.

2023-07-17 14:57 UTC, tnotheis approved these changes

2023-07-17 15:15 UTC, tnotheis commented
I removed the `bug` label because only bugs in the actual products (Consumer API, Admin UI, ...) should be labeled as such.

2023-07-18 05:56 UTC, tnotheis commented
@Dannyps Don't you want to merge this PR?

2023-07-18 06:00 UTC, Dannyps commented
Nah, it's good like this.

Kidding, I forgot 🤣 I was convinced I had set it to automerge.

2023-07-18 06:05 UTC, merged