Quota on Number of Tokens
nmshd/backbone pull request #235
Opened 2023-07-31 14:56 UTC by JLSRKonk

# Readiness checklist

- [x] I added/updated unit tests.
- [ ] I added/updated integration tests.
- [x] I ensured that the PR title is good enough for the changelog.
- [x] I labeled the PR.

2023-07-31 15:06 UTC, tnotheis requested changes

2023-07-31 15:06 UTC, tnotheis commented on Modules/Quotas/src/Quotas.Infrastructure/Persistence/Repository/TokensRepository.cs
> +        var relationshipsCount = await _tokensReadOnly.CountAsync(t => t.CreatedBy == createdBy.StringValue, cancellationToken);
```suggestion
        var relationshipsCount = await _tokensReadOnly.CountAsync(t => t.CreatedBy == createdBy, cancellationToken);
```

2023-07-31 15:17 UTC, JLSRKonk commented on Modules/Quotas/src/Quotas.Domain/Aggregates/Tokens/Token.cs
> +    public string Id { get; set; }
If we remove the Id from the Token class, we would also remove the `builder.HasKey(x => x.Id);` line from the TokenEntityTypeConfiguration, correct?

2023-08-01 12:56 UTC, tnotheis approved these changes

2023-08-01 12:59 UTC, merged