Quotas consistency check
nmshd/backbone pull request #241
Opened 2023-08-07 17:00 UTC by Dannyps

# Readiness checklist

- [x] I added/updated unit tests.
- [ ] I added/updated integration tests.
- [x] I ensured that the PR title is good enough for the changelog.
- [x] I labeled the PR.

2023-08-25 11:05 UTC, tnotheis requested changes

2023-08-25 11:05 UTC, tnotheis commented on Modules/Quotas/Quotas.Jobs.ConsistencyCheck/Infrastructure/ConsistencyCheck/ConsistencyCheck.cs
I am a little bit scared of the amount of data we have to load in memory for this job. Maybe we should run database queries that return only the faulty datasets. 🤔

2023-08-28 09:28 UTC, Dannyps commented on Modules/Quotas/Quotas.Jobs.ConsistencyCheck/Infrastructure/Persistence/Database/DevicesDbContext.cs
I was starting to reply to some other conversations opened in this review, but I figured this is the main point to settle, because if we go with Dapper, the other conversations cease to be relevant.

We make a somewhat extensive use of the ORM functionalities provided by EF Core here, and implementing the same logic with Dapper would probably result in a moderately complex query.

> Maybe we should run database queries that return only the faulty datasets. 

From this, my suggestion would go towards implementing the whole check as a database query (we were already contemplating a _moderately complex query_, might as well go all the way). And in doing it as such, I think it makes perfect sense to bring Dapper into the equation. However, I'm unsure that the structure of code we have right now is still a good fit -- my idea would be to find the discrepancies in the database, and not in memory like we're doing at the moment.

2023-08-28 11:45 UTC, tnotheis commented on Modules/Quotas/Quotas.Jobs.ConsistencyCheck/Infrastructure/Persistence/Database/DevicesDbContext.cs
> my idea would be to find the discrepancies directly in the database, and not in memory like we're doing at the moment.

That's what I meant with "run database queries that return only the faulty datasets."

2024-01-12 07:22 UTC, tnotheis commented
@daniel-almeida-konkconsulting How's your reviewing going? Remember to notify me once you're done so that I can start

2024-01-12 07:23 UTC, tnotheis commented
@daniel-almeida-konkconsulting Omg, I was on the wrong PR. 😆 Forget this.

2024-05-27 07:12 UTC, closed without merging