Admin UI frontend logging
nmshd/backbone pull request #252
Opened 2023-08-16 14:02 UTC by JLSRKonk

# Readiness checklist

-   [ ] I added/updated unit tests.
-   [x] I added/updated integration tests.
-   [x] I ensured that the PR title is good enough for the changelog.
-   [x] I labeled the PR.

2023-08-24 13:24 UTC, tnotheis requested changes

2023-08-24 13:24 UTC, tnotheis commented on AdminUi/src/AdminUi/Controllers/LogsController.cs
> +    private readonly ILoggerFactory _logger;
Why do you label it as a "logger" when in fact it is a "LoggerFactory"?

2023-08-24 13:24 UTC, tnotheis commented on AdminUi/src/AdminUi/Controllers/LogsController.cs
> +    public IActionResult CreateLog([FromBody] LogRequest request)
```suggestion
    public IActionResult CreateLog(LogRequest request)
```

It should automatically be read from the body.

2023-08-24 13:24 UTC, tnotheis commented on AdminUi/src/AdminUi/Controllers/LogsController.cs
> +    CRITICAL
Enum values in C# are usually not capitalized.

2023-08-24 13:24 UTC, tnotheis commented on AdminUi/test/AdminUi.Tests.Integration/Models/LogRequest.cs
> +    CRITICAL
Do caps

2023-08-24 13:24 UTC, tnotheis commented on AdminUi/test/AdminUi.Tests.Integration/StepDefinitions/LogsStepDefinitions.cs
> +            Arguments = Array.Empty<object>()
You should pass something here so that it is tested.

2023-08-24 13:24 UTC, tnotheis commented on AdminUi/test/AdminUi.Tests.Integration/StepDefinitions/LogsStepDefinitions.cs
> +            MessageTemplate = TestDataGenerator.GenerateString(12),
Pass some constant data instead of random values.

2023-08-24 13:24 UTC, tnotheis commented on AdminUi/test/AdminUi.Tests.Integration/StepDefinitions/LogsStepDefinitions.cs
> +            MessageTemplate = TestDataGenerator.GenerateString(12),
Use constant values

2023-08-24 13:24 UTC, tnotheis commented on AdminUi/src/AdminUi/ClientApp/src/app/services/logger-server-service/logger-server.service.ts
> +    public customiseRequestBody(metadata: INGXLoggerMetadata) {
Shouldn't this be an override as well?
```suggestion
    public override customiseRequestBody(metadata: INGXLoggerMetadata) {
```

2023-08-24 13:24 UTC, tnotheis commented on AdminUi/src/AdminUi/ClientApp/src/app/services/logger-server-service/logger-server.service.ts
> +        this.isLoggedIn$ = this.authService.isLoggedIn;
What is the dollar sign at the end of the variable for?

2023-08-24 13:24 UTC, tnotheis commented on AdminUi/src/AdminUi/ClientApp/src/app/services/logger-server-service/logger-server.service.ts
> +    isLoggedIn$: Observable<boolean> | undefined;
Why is it an `Observable<boolean>` and not just a `boolean`?

2023-08-24 13:24 UTC, tnotheis commented on AdminUi/src/AdminUi/ClientApp/src/app/app.module.ts
> +                serverLogLevel: NgxLoggerLevel.INFO,
Set it to error please.

2023-08-24 13:24 UTC, tnotheis commented on AdminUi/src/AdminUi/ClientApp/src/app/app.module.ts
> +                enableSourceMaps: true
What's this property for? To get better stacktraces?

2023-08-24 13:24 UTC, tnotheis commented
Did you try to add some log statements to see if it actually works?

2023-08-24 15:42 UTC, JLSRKonk commented
> Did you try to add some log statements to see if it actually works?

Yes, I tested logging in one of the components and the log is correctly logged to the console and a log request is sent to our logs endpoint with the correct data.

![image](https://github.com/nmshd/backbone/assets/118175875/d90f48bf-8936-4699-961f-e26cbfedef6c)

![Screenshot 2023-08-24 164021](https://github.com/nmshd/backbone/assets/118175875/5f312aee-4050-44d9-a4a5-a7fb43844d8a)

![Screenshot 2023-08-24 164125](https://github.com/nmshd/backbone/assets/118175875/083a7590-13d9-4fcd-811b-c490bbf7fabc)

2023-08-25 10:22 UTC, tnotheis commented on AdminUi/src/AdminUi/ClientApp/src/app/app.module.ts
> +                enableSourceMaps: true
Okay, that's what I expected. 👍

2023-08-25 10:24 UTC, tnotheis commented
> > Did you try to add some log statements to see if it actually works?
> 
> Yes, I tested logging in one of the components and the log is correctly logged to the console and a log request is sent to our logs endpoint with the correct data.
> 
> ![image](https://user-images.githubusercontent.com/118175875/263027458-d90f48bf-8936-4699-961f-e26cbfedef6c.png)
> 
> ![Screenshot 2023-08-24 164021](https://user-images.githubusercontent.com/118175875/263028237-5f312aee-4050-44d9-a4a5-a7fb43844d8a.png)
> 
> ![Screenshot 2023-08-24 164125](https://user-images.githubusercontent.com/118175875/263028459-083a7590-13d9-4fcd-811b-c490bbf7fabc.png)

The log message in the console looks weird. Is there a way to format it differently?

2023-08-25 10:28 UTC, tnotheis requested changes

2023-08-25 10:28 UTC, tnotheis commented on AdminUi/src/AdminUi/ClientApp/src/app/services/logger-server-service/logger-server.service.ts
> +        this.isLoggedIn$ = this.authService.isLoggedIn;
1. Why don't you use the HttpClient then?
2. I still don't understand what the dollar sign is for.

2023-08-25 10:28 UTC, tnotheis commented on AdminUi/src/AdminUi/ClientApp/src/app/services/logger-server-service/logger-server.service.ts
> +    isLoggedIn$: Observable<boolean> | undefined;
What about this?

2023-08-25 14:40 UTC, JLSRKonk commented
I'm going to try and explain everything in this comment.

`isLoggedIn$`$ is an Observable, and Observables typically have a "$" suffix in order to identify them at first glance.
[Angular Source](https://angular.io/guide/rx-library#naming-conventions-for-observables)

Why is `isLoggedIn$` an Observable?
This is our current implementation of the interceptor:
![image](https://github.com/nmshd/backbone/assets/118175875/f177e275-3ee9-47b0-b062-025956ed34e8)
The `isLoggedIn$` is a reference to the `authService.isLoggedIn` method.
![image](https://github.com/nmshd/backbone/assets/118175875/af9a0e61-85b9-4c74-8bec-76c0daa76ae5)
The `isLoggedIn` method returns the `LoggedIn` variable, which is a BehaviorSubject on the `this.hasApiKey()` method. I assume we return a BehaviorSubject and not a boolean directly for better performance.

Why don't we use the `HttpClient` instead of `HttpBackend` to avoid duplicating code?
Well, the ngx logger library uses the `HttpBackend` for all its logging calls.
The logger-server-service I created for this task extends their `NGXLoggerServerService` and overrides a few of their methods in order to modify the `HttpRequest` that we send, so I can't really swap out `HttpBacked` for `HttpClient` without rewriting their service.
[Service Source Code](https://github.com/dbfannin/ngx-logger/blob/master/src/lib/server/server.service.ts#L16)

And finally, regarding the log message on the console.
We can override the log method from NGXLoggerWriterService to make it look exactly how we want, do you have any suggestions on what the message should look like in the console?
[Service Source Code](https://github.com/dbfannin/ngx-logger/blob/master/src/lib/writer/writer.service.ts#L96)

In the screenshot I used the following logging command:
`this.logger.error("The page {0} has the following description: {1}", this.header, this.displayedColumns);`
Using {0} and {1} for the logger in .NET to auto replace them with the arguments.

2023-08-28 12:01 UTC, tnotheis commented
> The isLoggedIn method returns the LoggedIn variable, which is a BehaviorSubject on the this.hasApiKey() method. I assume we return a BehaviorSubject and not a boolean directly for better performance.

Okay. I don't want to say that I understand it but I can live with it. :)

> I can't really swap out HttpBacked for HttpClient without rewriting their service.

I didn't see that the base constructor needs this dependency. What if you simply add another dependency for the HttpClient and ignore the HttpBackend?
Do you know why they even use the HttpBackend? Are there any performance implications when using HttpClient?

> do you have any suggestions on what the message should look like in the console?

Well, just like in the Backend. So the placeholders should be replaced with their values, instead of logging the log message with the placeholders followed by the values.

2023-08-28 12:50 UTC, JLSRKonk commented
> > The isLoggedIn method returns the LoggedIn variable, which is a BehaviorSubject on the this.hasApiKey() method. I assume we return a BehaviorSubject and not a boolean directly for better performance.
> 
> Okay. I don't want to say that I understand it but I can live with it. :)
> 
> > I can't really swap out HttpBacked for HttpClient without rewriting their service.
> 
> I didn't see that the base constructor needs this dependency. What if you simply add another dependency for the HttpClient and ignore the HttpBackend? Do you know why they even use the HttpBackend? Are there any performance implications when using HttpClient?
> 
> > do you have any suggestions on what the message should look like in the console?
> 
> Well, just like in the Backend. So the placeholders should be replaced with their values, instead of logging the log message with the placeholders followed by the values.

I was looking the their service source code and they have this comment:

![image](https://github.com/nmshd/backbone/assets/118175875/80d10e99-9251-46d7-b31a-10720ec5e713)

I'm not sure if this concern even applies to our project.
If not, I can override their logOnServer() method, and just swap every use of HttpBackend with the HttpClient. This way we won't need to duplicate the interceptor logic here.

2023-08-28 13:15 UTC, tnotheis commented
> > > The isLoggedIn method returns the LoggedIn variable, which is a BehaviorSubject on the this.hasApiKey() method. I assume we return a BehaviorSubject and not a boolean directly for better performance.
> > 
> > 
> > Okay. I don't want to say that I understand it but I can live with it. :)
> > > I can't really swap out HttpBacked for HttpClient without rewriting their service.
> > 
> > 
> > I didn't see that the base constructor needs this dependency. What if you simply add another dependency for the HttpClient and ignore the HttpBackend? Do you know why they even use the HttpBackend? Are there any performance implications when using HttpClient?
> > > do you have any suggestions on what the message should look like in the console?
> > 
> > 
> > Well, just like in the Backend. So the placeholders should be replaced with their values, instead of logging the log message with the placeholders followed by the values.
> 
> I was looking the their service source code and they have this comment:
> 
> ![image](https://user-images.githubusercontent.com/118175875/263704365-80d10e99-9251-46d7-b31a-10720ec5e713.png)
> 
> I'm not sure if this concern even applies to our project. If not, I can override their logOnServer() method, and just swap every use of HttpBackend with the HttpClient. This way we won't need to duplicate the interceptor logic here.

Oh man, I should have looked at your code in more detail. Sorry. I didn't even notice that the method containing the authorization stuff is only altering the http request and not sending it. I guess I'm okay with it then.

2023-08-29 07:50 UTC, tnotheis requested changes

2023-08-29 07:50 UTC, tnotheis commented on AdminUi/src/AdminUi/ClientApp/src/app/services/logger-server-service/logger-server.service.ts
> +            messageTemplate = messageTemplate.replace("%s", `{${i}}`);
What if I want to actually log "%s"? Or what if I use "%d" for example?

You should therefore use the following regex:

```
(?<!%)%[dsj]
```

2023-08-30 12:09 UTC, tnotheis commented on AdminUi/src/AdminUi/ClientApp/src/app/services/logger-server-service/logger-server.service.ts
> +            messageTemplate = messageTemplate.replace(new RegExp("(?<!%)%[dsj]"), `{${i}}`);
If yes, feel free to merge.

2023-08-30 12:09 UTC, tnotheis approved these changes

2023-08-30 12:57 UTC, merged