Quota on Number of RelationshipTemplates
nmshd/backbone pull request #287
Opened 2023-09-12 12:50 UTC by JLSRKonk

# Readiness checklist

-   [x] I added/updated unit tests.
-   [ ] I added/updated integration tests.
-   [x] I ensured that the PR title is good enough for the changelog.
-   [x] I labeled the PR.

2023-09-12 13:59 UTC, Dannyps commented on Modules/Relationships/test/Relationships.Application.Tests/Tests/RelationshipTemplates/Commands/CreateRelationshipTemplate/HandlerTests.cs
> +        A.CallTo(() => _eventBus.Publish(A<IntegrationEvent>.That.IsInstanceOf(typeof(RelationshipTemplateCreatedIntegrationEvent)))).MustHaveHappened();
```suggestion
        A.CallTo(() => _eventBus.Publish(A<RelationshipTemplateCreatedIntegrationEvent>._).MustHaveHappened();
```

Wouldn't this work?

2023-09-12 14:12 UTC, daniel-almeida-konkconsulting requested changes

2023-09-12 14:12 UTC, daniel-almeida-konkconsulting commented on Modules/Quotas/src/Quotas.Infrastructure/Persistence/Repository/RelationshipTemplatesRepository.cs
> +internal class RelationshipTemplatesRepository : IRelationshipTemplatesRepository
Why is this class internal?

2023-09-12 14:12 UTC, daniel-almeida-konkconsulting commented on Modules/Quotas/src/Quotas.Infrastructure/Persistence/Repository/RelationshipTemplatesRepository.cs
> +    private readonly IQueryable<RelationshipTemplate> _templatesReadOnly;
We typically name these variables with readOnly as a prefix and not a suffix (e.g., _readOnlyTemplates)

2023-09-12 14:12 UTC, daniel-almeida-konkconsulting commented on Modules/Quotas/src/Quotas.Application/IntegrationEvents/Incoming/RelationshipTemplateCreated/RelationshipTemplateCreatedIntegrationEventHandler.cs
> +internal class RelationshipTemplateCreatedIntegrationEventHandler : IIntegrationEventHandler<RelationshipTemplateCreatedIntegrationEvent>
Why is this class internal?

2023-09-12 14:12 UTC, daniel-almeida-konkconsulting commented on Modules/Quotas/src/Quotas.Application/Metrics/NumberOfRelationshipTemplatesMetricCalculator.cs
> +internal class NumberOfRelationshipTemplatesMetricCalculator : IMetricCalculator
Another internal class.

2023-09-12 14:12 UTC, daniel-almeida-konkconsulting commented on Modules/Quotas/src/Quotas.Infrastructure/Persistence/Repository/RelationshipTemplatesRepository.cs
> +        var tokensCount = await _templatesReadOnly.CountAsync(t => t.CreatedBy == createdBy.StringValue, cancellationToken);
Why is this variable named tokensCount?

2023-09-13 12:53 UTC, daniel-almeida-konkconsulting submitted a review, later dismissed

2023-09-18 08:32 UTC, tnotheis requested changes
Did you try to create a quota on this metric via the Admin UI?

2023-09-18 08:32 UTC, tnotheis commented on Modules/Quotas/src/Quotas.Infrastructure/Persistence/Database/QuotasDbContext.cs
> +
Remove this empty line

2023-09-18 08:46 UTC, JLSRKonk commented
The creation of the quota through the adminUi works:

![image](https://github.com/nmshd/backbone/assets/118175875/3b5cc98c-430f-4b68-836b-a0c6f81a5d2a)

![image](https://github.com/nmshd/backbone/assets/118175875/9e658167-e82f-413b-92b5-308d1afdc094)

![image](https://github.com/nmshd/backbone/assets/118175875/a0158344-93bb-40d3-9db9-40d228b4c236)

2023-09-18 08:48 UTC, tnotheis approved these changes

2023-09-18 08:54 UTC, merged