Tiers: Show number of Identities
nmshd/backbone pull request #291
Opened 2023-09-13 14:26 UTC by JLSRKonk

# Readiness checklist

-   [x] I added/updated unit tests.
-   [x] I added/updated integration tests.
-   [x] I ensured that the PR title is good enough for the changelog.
-   [x] I labeled the PR.

2023-09-13 14:30 UTC, JLSRKonk commented
**Screenshots**

![image](https://github.com/nmshd/backbone/assets/118175875/454e8dac-1ca7-4637-8d05-8ae35009b8ea)

![image](https://github.com/nmshd/backbone/assets/118175875/97548287-f781-4754-a36a-789522cce7bd)

2023-09-13 17:16 UTC, daniel-almeida-konkconsulting requested changes

2023-09-13 17:16 UTC, daniel-almeida-konkconsulting commented on AdminUi/test/AdminUi.Tests.Integration/Models/TierDetailsDTO.cs
> +    public int? NumberOfIdentities { get; set; }
Why nullable?

2023-09-13 17:16 UTC, daniel-almeida-konkconsulting commented on AdminUi/test/AdminUi.Tests.Integration/Models/TierOverviewDTO.cs
> +    public int? NumberOfIdentities { get; set; }
Why nullable?

2023-09-13 17:16 UTC, daniel-almeida-konkconsulting commented on Modules/Quotas/src/Quotas.Application/Tiers/Queries/GetTierById/Handler.cs
> +        var identitiesCount = identities.Count();
Inline the Count() call and rename the variable (e.g., identitiesWithTierCount)

2023-09-14 09:04 UTC, daniel-almeida-konkconsulting submitted a review, later dismissed

2023-09-18 09:01 UTC, tnotheis requested changes
Did you test this on the Admin UI with Postgres as well as SQL Server?

2023-09-18 09:42 UTC, JLSRKonk commented on AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/tier/tier-edit/tier-edit.component.ts
> +                        quotas: [],
Currently, the POST Tier endpoint, returns a CreateTierResponse which contains only an Id and a Name and as the quotas field is required, we need to set it to a value. Setting it to an empty array, guarantees that the TierQuotas table and the add TierQuotas function don't break due to undefined fields.

2023-09-18 09:53 UTC, tnotheis commented on AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/tier/tier-edit/tier-edit.component.ts
> +                        quotas: [],
Oh, yeah, got it. Thanks

2023-09-18 11:23 UTC, JLSRKonk commented
I tested both SqlServer and Postgres, from fresh databases, and it is working as intended.

2023-09-18 11:34 UTC, tnotheis commented
Great. 

Remember to request review once you're done.

Btw: you don't have to/shouldn't always test with fresh databases. The 99% case is an already existing database.

2023-09-20 07:29 UTC, tnotheis requested changes

2023-09-20 07:29 UTC, tnotheis commented on AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/tier/tier-edit/tier-edit.component.ts
> +            deleteable: true
Should be `false` by default. I prefer that things are not deletable when they should be, rather than the other way around.

2023-09-20 07:29 UTC, tnotheis commented on AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/tier/tier-edit/tier-edit.component.ts
> +                    this.tier.name == "Basic" ? (this.tier.deleteable = false) : (this.tier.deleteable = true);
What is this? You couldn't have made this more complicated, could you?

```suggestion
                    this.tier.deleteable = this.tier.name == "Basic"
```

2023-09-20 07:29 UTC, tnotheis commented on AdminUi/src/AdminUi/ClientApp/src/app/components/quotas/tier/tier-edit/tier-edit.component.html
> +        <button *ngIf="editMode" mat-button color="warn" (click)="openConfirmationDialogTierDeletion()" [disabled]="tier.name == 'Basic' || tier.numberOfIdentities > 0">Delete</button>
`isDeletable`... Not `deletable`.

2023-09-20 09:22 UTC, tnotheis approved these changes

2023-09-20 09:36 UTC, merged