TierQuotaDefinitions are not deleted
nmshd/backbone pull request #330
Opened 2023-10-12 13:35 UTC by Dannyps

# Readiness checklist

-   [x] I added/updated unit tests.
-   [x] I added/updated integration tests.
-   [x] I ensured that the PR title is good enough for the changelog.
-   [x] I labeled the PR.

2023-10-13 14:03 UTC, Dannyps commented on Modules/Quotas/src/Quotas.Infrastructure/Persistence/Repository/TiersRepository .cs
> +
I'm unsure about this Exception

2023-10-17 07:23 UTC, tnotheis requested changes

2023-10-17 08:32 UTC, Dannyps commented on Modules/Quotas/src/Quotas.Domain/Aggregates/Identities/TierQuota.cs
> +    internal readonly TierQuotaDefinition _definition;
This was necessary to set the cascade behaviour on the `TierQuotaEntityTypeConfiguration.cs` file.

2023-10-17 09:18 UTC, tnotheis commented on Modules/Quotas/src/Quotas.Domain/Aggregates/Identities/TierQuota.cs
> +    internal readonly TierQuotaDefinition _definition;
As I said: 

> Afaik they can work with private fields as well. Did you try it or was it just an assumption?

2023-10-17 09:20 UTC, tnotheis commented on Modules/Quotas/src/Quotas.Domain/Aggregates/Identities/TierQuota.cs
> +    internal readonly TierQuotaDefinition _definition;
Soo... does the following not work?

```c#
builder.HasOne("_definition").WithMany().OnDelete(DeleteBehavior.Cascade);
```

2023-10-17 09:20 UTC, Dannyps commented on Modules/Quotas/src/Quotas.Domain/Aggregates/Identities/TierQuota.cs
> +    internal readonly TierQuotaDefinition _definition;
Sorry. Yes, setting it to private throws a build error:

`Error	CS0122	'TierQuota._definition' is inaccessible due to its protection level	Quotas.Infrastructure	enmeshed\backbone\Modules\Quotas\src\Quotas.Infrastructure\Persistence\Database\EntityConfigurations\TierQuotaEntityTypeConfiguration.cs`

2023-10-17 09:25 UTC, Dannyps commented on Modules/Quotas/src/Quotas.Domain/Aggregates/Identities/TierQuota.cs
> +    internal readonly TierQuotaDefinition _definition;
Aye, that does work!

2023-10-17 09:53 UTC, tnotheis approved these changes

2023-10-17 10:19 UTC, merged