Consumer API: Fix nullability issues
nmshd/backbone pull request #509
Opened 2024-01-29 12:45 UTC by MH321Productions

# Readiness checklist

-   [ ] I added/updated unit tests.
-   [ ] I added/updated integration tests.
-   [x] I ensured that the PR title is good enough for the changelog.
-   [x] I labeled the PR.

2024-01-30 09:27 UTC, NikolaVetnic requested changes

2024-01-31 17:08 UTC, tnotheis commented on Modules/Files/src/Files.Infrastructure/Persistence/Database/IServiceCollectionExtensions.cs
> +    public string DbConnectionString { get; set; } = string.Empty;
null! should be the way to go in this case

2024-02-09 07:05 UTC, tnotheis commented
@MH321Productions I changed the title so it is consistent with the other PRs. In case of a refactoring, the prefix ("Consmumer API"/"Admin UI") isn't important, as they don't show up in the release notes anyway.

2024-02-09 12:01 UTC, tnotheis approved these changes

2024-02-09 12:55 UTC, NikolaVetnic approved these changes

2024-02-09 12:56 UTC, tnotheis approved these changes

2024-02-09 12:56 UTC, merged