Consumer API: Rename "IntegrationEvent" to "DomainEvent"
nmshd/backbone pull request #607
Opened 2024-04-17 14:04 UTC by MH321Productions

# Readiness checklist

-   [ ] I added/updated unit tests.
-   [ ] I added/updated integration tests.
-   [x] I ensured that the PR title is good enough for the changelog.
-   [x] I labeled the PR.

2024-04-18 12:40 UTC, tnotheis requested changes

2024-04-18 12:40 UTC, tnotheis commented on Modules/Devices/src/Devices.Application/Extensions/IServiceCollectionExtensions.cs
> +        var integrationEventHandlerTypes =
rename

2024-04-18 12:40 UTC, tnotheis commented on Modules/Quotas/src/Quotas.Application/Extensions/IEventBusExtensions.cs
>  using Backbone.Modules.Quotas.Application.IntegrationEvents.Incoming.TierQuotaDefinitionDeleted;
Why is there still the "IntegrationEvents" namespace?

2024-04-18 12:40 UTC, tnotheis commented on Modules/Quotas/src/Quotas.Application/Extensions/IServiceCollectionExtensions.cs
> +        var integrationEventHandlerTypes =
rename

2024-04-19 11:14 UTC, MH321Productions commented
I now performed a global find/replace in the files, as well as one for the file and directory names

2024-04-19 11:44 UTC, tnotheis approved these changes

2024-04-19 11:52 UTC, merged