Admin API Integration tests with Admin API SDK
nmshd/backbone pull request #609
Opened 2024-04-19 13:01 UTC by daniel-almeida-konkconsulting

# Readiness checklist

-   [ ] I added/updated unit tests.
-   [X] I added/updated integration tests.
-   [X] I ensured that the PR title is good enough for the changelog.
-   [X] I labeled the PR.

2024-04-19 14:54 UTC, Dannyps commented on AdminApi/test/AdminApi.Tests.Integration/AdminApi.Tests.Integration.csproj
> +      <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.3" />
fix indentation

2024-05-14 09:35 UTC, Dannyps commented on AdminApi/src/AdminApi/Extensions/ChallengesServiceCollectionExtensions .cs
there's a space in the name of the file

2024-05-14 09:41 UTC, daniel-almeida-konkconsulting commented on AdminApi/src/AdminApi/Program.cs
> +        .AddJsonFile("appsettings.override.json", true, true);
Resharper code cleanup, reverting.

2024-05-14 09:42 UTC, daniel-almeida-konkconsulting commented on AdminApi/src/AdminApi/Program.cs
> +            .Enrich.WithCorrelationId("X-Correlation-Id", true)
Resharper code cleanup, reverting.

2024-05-14 09:44 UTC, daniel-almeida-konkconsulting commented on AdminApi/test/AdminApi.Tests.Integration/StepDefinitions/IndividualQuotaStepDefinitions.cs
> +            ((int)_response!.Status).Should().Be(expectedStatusCode);
`expectedStatusCode` is int and there's no implicit operator or cast from `System.Net.HttpStatusCode` to `int`.

2024-05-14 09:49 UTC, daniel-almeida-konkconsulting commented on AdminApi/test/AdminApi.Tests.Integration/api.appsettings.local.override.json
I did since the `Modules` connection strings already default to SQL Server, but this one was set to `Postgres`.
With this change they are at least consistent.

2024-05-14 10:08 UTC, daniel-almeida-konkconsulting commented on AdminApi/test/AdminApi.Tests.Integration/StepDefinitions/IdentitiesApiStepDefinitions.cs
> -        _identityOverviewsResponse!.AssertContentTypeIs("application/json");
Agreed.

2024-05-14 10:29 UTC, Dannyps approved these changes

2024-05-15 14:33 UTC, tnotheis requested changes

2024-05-15 14:33 UTC, tnotheis commented on AdminApi.Sdk/Endpoints/Messages/Types/MessageType.cs
> +    public string Value { get; }
Properties belong below the constructor

2024-05-15 14:33 UTC, tnotheis commented on AdminApi.Sdk/Services/IdentityCreationHelper.cs
> +    public async Task<ApiResponse<CreateIdentityResponse>?> CreateIdentity()
This can be a static method

2024-05-15 14:33 UTC, tnotheis commented on AdminApi/test/AdminApi.Tests.Integration/StepDefinitions/IndividualQuotaStepDefinitions.cs
> +        var createIdentityResponse = await accountController.CreateIdentity() ?? throw new InvalidOperationException();
What's this random InvalidOperationException? When can the response be null?

2024-05-15 14:33 UTC, tnotheis commented on AdminApi/test/AdminApi.Tests.Integration/StepDefinitions/MessagesStepDefinitions.cs
> +        var createIdentityResponse = await accountController.CreateIdentity() ?? throw new InvalidOperationException();
See above

2024-05-15 14:35 UTC, tnotheis commented on AdminApi/test/AdminApi.Tests.Integration/api.appsettings.local.override.json
I don't see an answer to this question.

2024-05-15 14:36 UTC, daniel-almeida-konkconsulting commented on AdminApi.Sdk/Services/IdentityCreationHelper.cs
> +    public async Task<ApiResponse<CreateIdentityResponse>?> CreateIdentity()
How? We need the client.

2024-05-15 15:08 UTC, merged