Admin API SDK: Add List Identities Route
nmshd/backbone pull request #612
Opened 2024-04-22 12:32 UTC by MH321Productions

# Readiness checklist

-   [ ] I added/updated unit tests.
-   [ ] I added/updated integration tests.
-   [x] I ensured that the PR title is good enough for the changelog.
-   [x] I labeled the PR.

2024-04-22 14:12 UTC, MH321Productions commented on AdminApi.Sdk/Endpoints/Identities/IdentitiesEndpoint.cs
> +    public async Task<ApiResponse<ListIdentitiesResponse>> ListIdentities() => await _client.Request<ListIdentitiesResponse>(HttpMethod.Get, "../../odata/Identities")
> Wtf, does the `../../` actually work in a URL? 😮

It actually does 🤣

2024-04-22 14:14 UTC, tnotheis commented on AdminApi.Sdk/Endpoints/Identities/IdentitiesEndpoint.cs
> +    public async Task<ApiResponse<ListIdentitiesResponse>> ListIdentities() => await _client.Request<ListIdentitiesResponse>(HttpMethod.Get, "../../odata/Identities")
Wow, I did not know this was a thing. 🤣

2024-04-23 16:39 UTC, daniel-almeida-konkconsulting commented on BuildingBlocks/src/BuildingBlocks.SDK/Endpoints/Common/EndpointClient.cs
> +            if (index > 0) str = str[..index] + ODATA_REPLACE + str[(index + ODATA_SEARCH.Length)..];
Keep in mind there are other differences between the response payloads.
OData, for example, adds a `@odata.context` property (e.g., `"@odata.context":"http://localhost/odata/$metadata#Identities"`)

2024-04-24 07:52 UTC, MH321Productions commented on BuildingBlocks/src/BuildingBlocks.SDK/Endpoints/Common/EndpointClient.cs
> +            if (index > 0) str = str[..index] + ODATA_REPLACE + str[(index + ODATA_SEARCH.Length)..];
Well, do I need to extract those?

2024-04-24 07:59 UTC, daniel-almeida-konkconsulting commented on BuildingBlocks/src/BuildingBlocks.SDK/Endpoints/Common/EndpointClient.cs
> +            if (index > 0) str = str[..index] + ODATA_REPLACE + str[(index + ODATA_SEARCH.Length)..];
Ideally, yes.
If what we are striving for is an exact match between both response, we should only have a result property for success cases. This is especially true when considering that the schema validation is made against the Raw Content of the response (hence an odata.context property will cause it to fail).

2024-04-24 08:04 UTC, MH321Productions commented on BuildingBlocks/src/BuildingBlocks.SDK/Endpoints/Common/EndpointClient.cs
> +            if (index > 0) str = str[..index] + ODATA_REPLACE + str[(index + ODATA_SEARCH.Length)..];
It doesn't fail. My current class looks like this:

```c#
public class ODataResponse<TResult>
{
    public TResult? Value { get; set; }

    public ApiResponse<TResult> ToApiResponse(HttpStatusCode status) => new() { Result = Value, Status = status };
}
```

I tested it and it works flawlessly. But if you want, I can make this class a wrapper with the context and the value and put this in the ```ApiResponse``` as ```ApiResponse<ODataReponse<T>>```.

2024-04-24 08:47 UTC, MH321Productions commented on BuildingBlocks/src/BuildingBlocks.SDK/Endpoints/Common/EndpointClient.cs
> +            if (index > 0) str = str[..index] + ODATA_REPLACE + str[(index + ODATA_SEARCH.Length)..];
Note to outside readers: Daniel and me had a misunderstanding and we resolved it privately.

2024-04-24 08:50 UTC, tnotheis requested changes
I let @daniel-almeida-konkconsulting do the final review. As soon as he approved I will give my approval as well (this is required because I'm code owner)

2024-04-24 08:50 UTC, tnotheis commented on BuildingBlocks/src/BuildingBlocks.SDK/Endpoints/Common/EndpointClient.cs
> +    private const string ODATA_REPLACE = "result";
These are not used

2024-04-24 08:59 UTC, MH321Productions commented on BuildingBlocks/src/BuildingBlocks.SDK/Endpoints/Common/EndpointClient.cs
> +    private const string ODATA_REPLACE = "result";
Touché

2024-05-06 06:17 UTC, tnotheis requested changes

2024-05-06 06:17 UTC, tnotheis commented on AdminApi.Sdk/Endpoints/Identities/Types/Requests/CreateIdentityRequest.cs
> +    public required string IdentityPublicKey { get; set; }
Why didn't you keep the byte[] type? Imo it's better, because in case of a string, you don't know that it has to be base64 encoded.

2024-05-06 06:17 UTC, tnotheis commented on AdminApi.Sdk/Services/AccountController.cs
Why is this class part of a PR with the name "Add List Identities Route"?

2024-05-06 15:11 UTC, merged