Add /Tier POST to Admin API
nmshd/backbone pull request #62
Opened 2023-04-04 13:34 UTC by Dannyps

2023-04-05 06:55 UTC, tnotheis commented
This branch needs to be synced with main

2023-04-05 07:14 UTC, Dannyps commented
@tnotheis, yesterday @daniel-almeida-konkconsulting mentioned you may prefer this PR to target the parent branch of the branch to be merged, which is `feature/DEV-1808-admin-api-identities-list` (#46).
Should I change the base, or sync this wih `main`?

2023-04-05 07:24 UTC, tnotheis commented
@Dannyps Sorry, my bad. I meant the base branch, of course.

2023-04-05 11:27 UTC, tnotheis requested changes
Shouldn't the target branch of this PR be the `feature/create-tier` branch?

2023-04-05 14:35 UTC, Dannyps commented
I believe I've fixed this as best I can. The `feature/create-tier` branch does not have anything related to the Admin.API.

The way I see it, we can either bring the Admin API to it via this PR, or we can merge main to it, strip the Admin.API commits from this PR, and merge.

2023-04-06 14:12 UTC, tnotheis requested changes
There are no integration tests for the route.

2023-04-06 14:12 UTC, tnotheis commented on Modules/Devices/src/Devices.Application/Infrastructure/Persistence/Repository/IIdentityRepository.cs
> +public interface IIdentityRepository
```suggestion
public interface IIdentitiesRepository
```

2023-04-06 14:12 UTC, tnotheis commented on Modules/Devices/src/Devices.Infrastructure/Persistence/Repository/IdentityRepository.cs
> +        _identityDbSet = dbContext.Identities;
Remove this as long as we don't need it, please.

2023-04-06 14:12 UTC, tnotheis commented on Modules/Devices/test/Devices.API.Tests.Integration/Models/IdentityResponse.cs
> +namespace Challenges.API.Tests.Integration.Models;
Wrong Namespace

2023-04-06 14:20 UTC, tnotheis approved these changes

2023-04-06 14:20 UTC, merged