Auto create basic tier
nmshd/backbone pull request #64
Opened 2023-04-04 15:36 UTC by Dannyps

2023-04-05 11:26 UTC, tnotheis requested changes
There is something wrong with this PR. There are lots of changes in here that @daniel-almeida-konkconsulting made on another branch.

2023-04-05 11:26 UTC, tnotheis commented on Backbone.API/ApplicationDbContextSeed.cs
> +        await context.Tiers.AddAsync(new Tier(TierName.Create("Basic Tier").Value));
The Tier name shouldn't contain the word "Tier". That's redundant.

2023-04-05 12:27 UTC, Dannyps commented
This branch was based on `feature/create-tier--create-tier-command` but that branch does not seem to exist anymore, so I set `feature/create-tier` as base instead.

2023-04-05 12:31 UTC, tnotheis commented
Take a look at the diff. There is some pipeline stuff listed that shouldn't be there

2023-04-05 13:21 UTC, Dannyps commented
Sorry for the force, I couldn't revert a merge commit that was poisioning the PR. It should be good now.

2023-04-06 14:59 UTC, tnotheis requested changes
Just noticed that there is a naming error on the APplicationDbContextSeed class, which originates from the microservice times.
The class should be called `DevicesDbContextSeed`. Could you fix that please?

2023-04-06 15:33 UTC, tnotheis approved these changes

2023-04-06 15:34 UTC, merged