Merge main into release/v5
nmshd/backbone pull request #696
Opened 2024-06-12 12:02 UTC by daniel-almeida-konkconsulting

# Readiness checklist

-   [X] I added/updated unit tests.
-   [X] I added/updated integration tests.
-   [X] I ensured that the PR title is good enough for the changelog.
-   [X] I labeled the PR.

2024-06-12 13:13 UTC, MH321Productions requested changes

2024-06-12 13:13 UTC, MH321Productions commented on Modules/Relationships/test/Relationships.Application.Tests/Tests/RelationshipTemplates/Commands/CreateRelationshipTemplate/HandlerTests.cs
You can remove the `Triggers_RelationshipTemplateCreatedDomainEvent` method (and therefore the whole file), as it's not needed anymore

2024-06-12 13:13 UTC, MH321Productions commented on Modules/Relationships/test/Relationships.Application.Tests/Tests/Relationships/Commands/CreateRelationship/HandlerTests.cs
You can remove the `Publishes_RelationshipStatusChangedDomainEvent` method, as it's not needed anymore.

2024-06-13 05:59 UTC, tnotheis commented on Modules/Relationships/test/Relationships.Application.Tests/Tests/RelationshipTemplates/Commands/CreateRelationshipTemplate/HandlerTests.cs
Confirmed.

2024-06-13 05:59 UTC, tnotheis commented on Modules/Relationships/test/Relationships.Application.Tests/Tests/Relationships/Commands/CreateRelationship/HandlerTests.cs
Confirmed.

2024-06-24 06:26 UTC, tnotheis approved these changes

2024-06-24 07:07 UTC, tnotheis approved these changes

2024-06-24 07:08 UTC, merged