Consumer API: Anonymization of Message Participants when Relationship Terminated
nmshd/backbone pull request #727
Opened 2024-07-03 16:24 UTC by daniel-almeida-konkconsulting

# Readiness checklist

-   [X] I added/updated unit tests.
-   [ ] I added/updated integration tests.
-   [X] I ensured that the PR title is good enough for the changelog.
-   [X] I labeled the PR.

2024-07-04 09:55 UTC, Dannyps commented on Modules/Messages/src/Messages.Application/DomainEvents/Incoming/RelationshipStatusChanged/RelationshipStatusChangedDomainEventHandler.cs
> +        await _messagesRepository.Update(messagesExchangedBetweenRelationshipParticipants);
Shouldn't these operations depend on a specific new status instead of running for all except `ReadyForDeletion`?

2024-07-04 13:43 UTC, Dannyps submitted a review, later dismissed

2024-07-05 05:24 UTC, tnotheis commented
@Dannyps Can you manually test this please?

2024-07-05 06:01 UTC, tnotheis requested changes

2024-07-05 07:06 UTC, Dannyps commented on Modules/Messages/test/Messages.Domain.Tests/Messages/ExpressionTests.cs
https://github.com/nmshd/backbone/blob/7c899a266e420fa3295844d6b3d1800e226c1e71/Modules/Relationships/test/Relationships.Domain.Tests/Tests/Aggregates/Relationships/ExpressionTests.cs#L9-L21

@tnotheis I said the same, but there's a precedent already

2024-07-05 07:21 UTC, tnotheis commented on Modules/Messages/test/Messages.Domain.Tests/Messages/ExpressionTests.cs
Yeah, I've seen that a few days ago. @daniel-almeida-konkconsulting Can you update both places please? :)

2024-07-05 09:38 UTC, daniel-almeida-konkconsulting commented on Modules/Messages/test/Messages.Domain.Tests/Messages/MessageTests.cs
> +    public void SanitizeAfterRelationshipDeleted_Anonymizes_Recipient_Only_When_Other_Recipients_Exist()
Would `SanitizeAfterRelationshipDeleted_only_anonymizes_recipient_and_not_sender_when_other_recipients_exist` be better?

2024-07-05 09:43 UTC, tnotheis commented on Modules/Messages/test/Messages.Domain.Tests/Messages/MessageTests.cs
> +    public void SanitizeAfterRelationshipDeleted_Anonymizes_Recipient_Only_When_Other_Recipients_Exist()
Ahh, now I get what you meant. :) Yes, the new one is better (at least for me ;))

2024-07-05 10:17 UTC, daniel-almeida-konkconsulting commented on Modules/Messages/test/Messages.Domain.Tests/Messages/ExpressionTests.cs
Updated.
Also added the missing Arrange, Act and Assert comments.

2024-07-05 11:02 UTC, tnotheis approved these changes

2024-07-05 11:33 UTC, merged