Implementation of the first performance test scenario
nmshd/backbone pull request #785
Opened 2024-08-01 07:25 UTC by Dannyps

# Readiness checklist

-   [ ] I added/updated unit tests.
-   [ ] I added/updated integration tests.
-   [x] I ensured that the PR title is good enough for the changelog.
-   [x] I labeled the PR.

2024-09-03 15:39 UTC, Dannyps commented
I have added a small utility which can be used to analyze the output of k6.

Example:

```
# node .\result-analyzer\src\main.js .\result.csv 
HTTP Request Metrics Grouped by Route and Type:

 ===

Route: /connect/token
Total Requests: 107
Status Codes:
  200: 107
Timings:
http_req_duration:       524.23 ms
http_req_blocked:        0.02 ms
http_req_connecting:     0.01 ms
http_req_tls_handshaking:        0.00 ms
http_req_sending:        0.06 ms
http_req_waiting:        523.90 ms
http_req_receiving:      0.26 ms
http_req_failed:         0.00 ms

 ===

Route: /api/v1/Challenges
Total Requests: 107
Status Codes:
  201: 107
Timings:
http_req_duration:       290.02 ms
http_req_blocked:        0.01 ms
http_req_connecting:     0.00 ms
http_req_tls_handshaking:        0.00 ms
http_req_sending:        0.02 ms
http_req_waiting:        277.18 ms
http_req_receiving:      12.81 ms
http_req_failed:         0.00 ms
```

2024-09-04 06:27 UTC, tnotheis commented
> I have added a small utility which can be used to analyze the output of k6.

1. This utility should be part of the script that is used to run the tests, so that you don't have to know/remember to call the script.
2. What does "Type" mean? ("HTTP Request Metrics Grouped by Route and **Type**"

2024-09-04 06:28 UTC, tnotheis commented
Oh, and 3. what if there are for example `GET /Tokens` and `POST /Tokens`? Currently, your output only shows the rquest path, not the request method.

2024-09-04 09:31 UTC, Dannyps commented
I've changes the output to group by and include the method:

```
Route: POST /connect/token
Total Requests: 31
Status Codes:
  200: 31
Timings:
http_req_duration:       193.00 ms
http_req_blocked:        0.06 ms
http_req_connecting:     0.04 ms
http_req_sending:        0.03 ms
http_req_waiting:        192.74 ms
http_req_receiving:      0.23 ms
http_req_failed:         0.00 ms

Route: POST /api/v1/Challenges
Total Requests: 31
Status Codes:
  201: 31
Timings:
http_req_duration:       121.26 ms
http_req_blocked:        0.00 ms
http_req_connecting:     0.00 ms
http_req_sending:        0.08 ms
http_req_waiting:        116.09 ms
http_req_receiving:      5.10 ms
http_req_failed:         0.00 ms
```

I have also created windows (PS) and Linux (bash) scripts that take care of compiling and running the test, and then calling the analyzer. Hence,

1. Fixed.
2. I've renamed type to timings
3. Fixed.

2024-09-05 07:12 UTC, tnotheis commented
I really don't like all the abbreviations you use throughout the code and readme files. This makes it so much harder to understand everything when you work with it for the first time.

2024-09-10 08:46 UTC, Dannyps commented
@tnotheis I cannot rerequest review here, but it should be good to go.

2024-09-11 11:06 UTC, tnotheis requested changes

2024-09-11 11:06 UTC, tnotheis commented on Applications/ConsumerApi/test/ConsumerApi.Tests.Performance/src/libs/backbone-client/fluent-client.ts
> +    public asJson(): this {
Shouldn't this rather be called seomething like "withJsonBody"? "asJson" looks as if the method would return a json representation of the FluentClient.

2024-09-11 11:06 UTC, tnotheis commented on Applications/ConsumerApi/test/ConsumerApi.Tests.Performance/src/libs/backbone-client/fluent-client.ts
> +export class FluentClient {
This class isn't stateless and therefore isn't thread safe. This will become a problem sooner or later.

2024-09-12 10:42 UTC, Dannyps commented on Applications/ConsumerApi/test/ConsumerApi.Tests.Performance/src/libs/file-utils.ts
I took some metrics:

| Snapshot | Load all entities                                 |
|----------|---------------------------------------------------|
| Light    | 700ms                                             |
| Heavy    | //k6 collapsed after allocating over ~16GB  of RAM |

| Snapshot | Load only identities |
|----------|---------------------------------------------------|
| Light    | 58ms |
| Heavy    | 67901ms |

| Snapshot | Load identities & RelationshipTemplates|
|----------|---------------------------------------------------|
| Light    | 407ms |
| Heavy    | //k6 collapsed after allocating over ~16GB  of RAM |

| Snapshot | Load identities & Relationships|
|----------|---------------------------------------------------|
| Light    | 77ms |
| Heavy    | 67772ms |

I must confess this is not what I was expecting.

2024-09-12 11:06 UTC, Dannyps commented
I must call attention to these results: https://github.com/nmshd/backbone/pull/785/files#r1756606368

2024-09-12 11:16 UTC, Dannyps commented on Applications/ConsumerApi/test/ConsumerApi.Tests.Performance/src/libs/file-utils.ts
loading the data only

2024-09-12 13:03 UTC, tnotheis commented on Applications/ConsumerApi/test/ConsumerApi.Tests.Performance/src/libs/file-utils.ts
Okay, I guess you have things to do then. :)

2024-09-12 13:17 UTC, Dannyps commented on Applications/ConsumerApi/test/ConsumerApi.Tests.Performance/src/libs/file-utils.ts
I'm investigating the possibility of storing the data as json, wondering if the bottleneck here is the parsing of the csv files. Do you have anything else in mind?

2024-09-12 13:28 UTC, tnotheis commented on Applications/ConsumerApi/test/ConsumerApi.Tests.Performance/src/libs/file-utils.ts
You're loading the full file content into memory. I don't know if it is cleaned up once you don't need it anymore (=> once you parsed it and created the corresponding object representations).

2024-09-12 13:38 UTC, Dannyps commented on Applications/ConsumerApi/test/ConsumerApi.Tests.Performance/src/libs/file-utils.ts
Well, me neither. We don't have control over memory management in Javascript. We must also consider that we're using a special engine developed in Go.
It's even possible that the same code would be much more performant when using nodejs, for instance.

2024-09-12 14:00 UTC, tnotheis commented on Applications/ConsumerApi/test/ConsumerApi.Tests.Performance/src/libs/file-utils.ts
Okay, then let's try to avoid the parsing by just saving the JSON. Maybe this already solves our problems.

2024-09-12 14:54 UTC, Dannyps commented on Applications/ConsumerApi/test/ConsumerApi.Tests.Performance/src/libs/file-utils.ts
Before moving to the json representation (it's not that trivial to get), I started taking some timings on the loading process and found a bug. I was actually loading every single relationship template for each identity (like a cross join). I'll be doing further tests to see how much more we can cut on loading times, but I've managed to load all of the the heavy pool in  a blazing fast 109.538s :)

2024-09-12 15:27 UTC, Dannyps commented on Applications/ConsumerApi/test/ConsumerApi.Tests.Performance/src/libs/file-utils.ts
Further optimisations have reduced this time to a bit over 5s on my machine. I'm good with this now.

2024-09-13 11:34 UTC, Dannyps commented on Applications/ConsumerApi/test/ConsumerApi.Tests.Performance/src/libs/file-utils.ts
5500ms for heavy, 230ms for light.

2024-09-16 09:05 UTC, tnotheis requested changes
I think we're getting there. :) These might actually be the last requested changes.

2024-09-18 07:46 UTC, Dannyps commented on Applications/ConsumerApi/test/ConsumerApi.Tests.Performance/src/libs/data-loader/models.ts
> +export class DataRepresentation implements IDataRepresentation {
This was called `DREPT`. It was an acronym, so it was renamed to `DataRepresentationForEnmeshedPerformanceTests`. Then we dropped the performance tests part and the Enmeshed. If I recall correctly, you said that it was obvious that this was about performance tests and Enmeshed, hence the change. Now it's so generic 🤷‍♂️

I honestly don't have a better suggestion here. I liked the acronym as a concept itself, once you aquired it, it felt graspable.

2024-09-18 07:46 UTC, Dannyps commented on Applications/ConsumerApi/test/ConsumerApi.Tests.Performance/src/libs/data-loader/models.ts
> +    public ofTypes = (...types: string[]): IDataRepresentation => new DataRepresentation(this._pools.filter((pool) => types.some((type) => pool.name.startsWith(type))));
We currently support the following pool types/aliases:
 - `e`: never
 - `a1`: app light
 - `a2`: app medium
 - `a3`: app heavy
 - `c1`: connector light
 - `c2`: connector medium
 - `c3`: connector heavy

The idea of this method is to load all pools starting with a certain letter. This comes from the assumption that we'll mostly be loading all a/c pools. If we change to `.withNames()`, and go ahead with the Enum, then a full list must be provided. I don't have an issue with that, but I want to make sure that is the expected change here.

2024-09-18 07:46 UTC, Dannyps commented on Applications/ConsumerApi/test/ConsumerApi.Tests.Performance/src/scenarios/s01.test.ts
> +    const currentIdentity = testIdentities[identityIterator++];
There's a possibility there could be an issue, yes. k6 does not facilitate a solution though. There is https://github.com/olegbespalov/xk6-atomic, but I'd rather avoid custom k6 implementations if possible.

As for the race condition, the truth is that k6 spreads the execution of VUs and respective iterations. Moreover, this being the first line of the default function, I don't expect different threads to become _entangled_. Regardless, I propose a change to further reduce the possibility of complications.

2024-09-18 08:40 UTC, tnotheis commented on Applications/ConsumerApi/test/ConsumerApi.Tests.Performance/src/libs/backbone-client/base-client.ts
> +            baseURL: defaultBaseUrl,
I don't like relying solely on environment variables. I often find it more appealing to use command line arguments. And this wouldn't work if the client reads the configuration from an env var.
Another reason for my suggestion is that if reading the env vars is split across multiple files, it hard to figure out what you can configure and what the names of the env vars are. If you have everything related to configuration in a single file though, this is much easier to figure out.

2024-09-18 08:55 UTC, tnotheis commented on Applications/ConsumerApi/test/ConsumerApi.Tests.Performance/src/libs/data-loader/models.ts
> +export class DataRepresentation implements IDataRepresentation {
How about "Identities"? :)

2024-09-18 08:58 UTC, tnotheis commented on Applications/ConsumerApi/test/ConsumerApi.Tests.Performance/src/libs/data-loader/models.ts
> +export class DataRepresentation implements IDataRepresentation {
> If I recall correctly, you said that it was obvious that this was about performance tests and Enmeshed
You are right. And I still think that `ForEnmeshedPerformanceTests` is redundant. My "so generic` was referring to the word "DataRepresentation". What is "Data"? And why is that "Data" not representative enough on its own?

2024-09-18 10:56 UTC, Dannyps commented on Applications/ConsumerApi/test/ConsumerApi.Tests.Performance/src/libs/backbone-client/base-client.ts
> +            baseURL: defaultBaseUrl,
It is not an env var. It's a cli parameter. It is done under the hood by k6.

2024-09-18 13:57 UTC, tnotheis commented on Applications/ConsumerApi/test/ConsumerApi.Tests.Performance/src/libs/backbone-client/base-client.ts
> +            baseURL: defaultBaseUrl,
Okay, but most of my arguments still apply:
- In order to figure out what arguments exist, you have to scan multiple files.
- You can only configure it using CLI parameters. Using env vars or config files is not possible.

2024-09-19 10:11 UTC, Dannyps commented on Applications/ConsumerApi/test/ConsumerApi.Tests.Performance/src/libs/data-loader/models.ts
> +export class DataRepresentation implements IDataRepresentation {
I've changed things around a bit. How about that?

2024-09-19 10:56 UTC, Dannyps commented on Applications/ConsumerApi/test/ConsumerApi.Tests.Performance/src/libs/backbone-client/base-client.ts
> +            baseURL: defaultBaseUrl,
I believe commit f33917d7e19e5535d1a689702b749854c18adebe addresses the issues you raised. 

However, please take into consideration that the `baseUrl` setting is silently overridden when the `--address=<host>:<port>` cli parameter is provided.

2024-09-19 14:51 UTC, tnotheis commented on Applications/ConsumerApi/test/ConsumerApi.Tests.Performance/src/libs/data-loader/models.ts
> +export class DataRepresentation implements IDataRepresentation {
Looks good

2024-10-02 11:23 UTC, tnotheis approved these changes

2024-10-02 12:31 UTC, tnotheis approved these changes

2024-10-02 13:07 UTC, merged