Consumer Api: Deletion of Files, Tokens and Relationship Templates
nmshd/backbone pull request #934
Opened 2024-11-06 14:12 UTC by MH321Productions

# Readiness checklist

-   [ ] I added/updated unit tests.
-   [x] I added/updated integration tests.
-   [x] I ensured that the PR title is good enough for the changelog.
-   [x] I labeled the PR.

2024-11-08 07:36 UTC, tnotheis requested changes

2024-11-11 13:36 UTC, MH321Productions commented on Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/Features/RelationshipTemplates/{id}/DELETE.feature
> +        And i sends a GET request to the /RelationshipTemplates/t.Id endpoint with password "-"
The "-" means that no password is used (I didn't want to write the same code again)

2024-11-11 13:40 UTC, MH321Productions commented on Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/Features/Tokens/{id}/DELETE.feature
> +        And Token t created by i with password "-" and forIdentity -
See above

2024-11-11 13:47 UTC, tnotheis commented on Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/Features/RelationshipTemplates/{id}/DELETE.feature
> +        And i sends a GET request to the /RelationshipTemplates/t.Id endpoint with password "-"
In my opinion having tests that have better readability is worth more than saving a little bit of code.

The step definitions with the `-` were written for tests where we had a table with input data. In that case it was handy to have something that meant "no password". But in this case you might as well just skip the whole password part.

2024-11-11 14:04 UTC, tnotheis requested changes

2024-11-11 14:04 UTC, tnotheis commented on Applications/ConsumerApi/test/ConsumerApi.Tests.Integration/StepDefinitions/TokensStepDefinitions.cs
> +    }
No need to support the anonymous case here.

```suggestion
    [When($@"{RegexFor.SINGLE_THING} sends a GET request to the /Tokens/{RegexFor.SINGLE_THING}.Id endpoint")]
    public async Task WhenIdentitySendsAGetRequestToTheTokensIdEndpoint(string identityName, string tokenName)
    {
        var client = _clientPool.FirstForIdentityName(identityName);
        var tokenId = _tokensContext.CreateTokenResponses[tokenName].Id;
        _responseContext.WhenResponse = await client.Tokens.GetToken(tokenId);
    }
```

2024-11-11 14:09 UTC, tnotheis approved these changes

2024-11-11 14:14 UTC, merged