Consumer Api: Lock password protected Tokens in case of too many failed attempts
nmshd/backbone pull request #997
Opened 2024-12-18 12:46 UTC by MH321Productions

# Readiness checklist

-   [x] I added/updated unit tests.
-   [x] I added/updated integration tests.
-   [x] I ensured that the PR title is good enough for the changelog.
-   [x] I labeled the PR.

2025-01-16 09:30 UTC, tnotheis requested changes
In the original task description, I forgot to mention that during identity deletion, the `TokenAllocation`s have to get anonymized. I updated the task description accordingly.

2025-01-16 09:30 UTC, tnotheis commented on Modules/Tokens/src/Tokens.Application/Tokens/Queries/GetToken/Handler.cs
> +        }
I'd suggest to extract more logic into the Token class. For example by doing something like this:

```c#
var error = token.TryToAccess(address, password);

if (error == null)
    return;

if(error == DomainErrors.WrongPassword()){
    await _tokensRepository.Update(token, cancellationToken);
    throw new NotFoundException(nameof(Token));
}

throw new DomainException(error);
```

This was just a quick try. I may have forgotten something or there may be a better way. But the big advantage of this is that the main part of the logic is now in Domain, which makes it a lot easier to test.

2025-01-16 09:30 UTC, tnotheis commented on Modules/Tokens/src/Tokens.Application/Tokens/Queries/GetToken/Handler.cs
> +            }
I think this stuff (except for line 46, of course) should also be placed into the `TryToAccess` method I suggested in the previous comment.

2025-01-16 09:30 UTC, tnotheis commented on Modules/Tokens/src/Tokens.Application/Tokens/Queries/ListTokens/ListTokensQuery.cs
Do we still need this? Can't we just pass a list of strings instead?

2025-01-16 09:30 UTC, tnotheis commented on Modules/Tokens/src/Tokens.Infrastructure/Persistence/Repository/TokensRepository.cs
> +            .Where(idFilter);
You should be able to simplify this query, now that we don't need to check the password anymore.

```c#
var query = (track ? _tokensDbSet : _readonlyTokensDbSet)
            .IncludeAll(_dbContext)
            .Where(Token.IsNotExpired)
            .Where(t => queryItems.Contains(t.Id)); // this line is new and replaces the foreach loop above)
```

2025-01-16 09:30 UTC, tnotheis commented on Modules/Tokens/test/Tokens.Domain.Tests/Tests/Token.AllocationTests.cs
All the tests need to be updated, of course, after extracting everything into a single domain method, as suggested above.

2025-01-16 11:54 UTC, MH321Productions commented on Modules/Devices/src/Devices.Infrastructure/Translations/Resources.pt.resx
> +    </data>
I've used the designer. I don't know why it is reversed 🤷

2025-01-16 12:18 UTC, MH321Productions commented on Modules/Tokens/src/Tokens.Application/Tokens/Queries/ListTokens/ListTokensQuery.cs
We don't need the query item, but we need the query. With the removal of the query item we can also remove them from the controller.

2025-01-16 12:24 UTC, MH321Productions commented on Modules/Tokens/src/Tokens.Application/Tokens/Queries/ListTokens/ListTokensQuery.cs
Does something use the new `tokens` query entry in `List Tokens`? Since they aren't needed anymore, I could remove it, but if some component depends on it, it would need to be kept for "backwards compatibility".

2025-02-03 13:53 UTC, tnotheis approved these changes

2025-02-03 14:02 UTC, merged