Abl 440 admin api for listing all tokens of an identity
nmshd/backbone pull request #999
Opened 2024-12-19 10:28 UTC by ericbrunner

# Readiness checklist

-   [ ] I added/updated unit tests.
-   [ ] I added/updated integration tests.
-   [x] I ensured that the PR title is good enough for the changelog.
-   [x] I labeled the PR.

2025-01-15 07:58 UTC, tnotheis requested changes
I know I told you it's not necessary to write an integration test for this  functionality (because we can't create tokens via the Admin API), but I just thought about it, and I think we could at least add one like "Listing all tokens of an identity that doesn't have any tokens".
This ensures that all DI wiring has been done correctly and that all dependencies can be resolved.

2025-01-15 07:58 UTC, tnotheis commented on Applications/AdminApi/src/AdminApi/Extensions/IServiceCollectionExtensions.cs
> +                ""));
Could you please add the TODO comment again?

2025-01-15 07:58 UTC, tnotheis commented on Applications/AdminApi/src/AdminApi/appsettings.json
Please keep the original formatting (4 space indentation).

2025-01-15 07:58 UTC, tnotheis commented on Applications/AdminApi/src/AdminApi/Extensions/TokensServiceCollectionExtensions.cs
> +        services.AddTransient<ITokensRepository, TokensRepository>();
Replace all of this with a call to `AddPersistence`:

```suggestion
        services.AddPersistence();
```

2025-01-15 07:58 UTC, tnotheis commented on Modules/Tokens/src/Tokens.Application/Tokens/Queries/ListTokensByIdentity/Validator.cs
Why do you use `CascadeMode.Stop` on every rule?

2025-01-15 11:06 UTC, ericbrunner commented on Modules/Tokens/src/Tokens.Application/Tokens/Queries/ListTokensByIdentity/Validator.cs
I grabbed the configuration from there: `Modules/Tokens/src/Tokens.Application/Tokens/Queries/ListTokens/Validator.cs`
probably it is not required. So I'll remove the call to Cascade 'cause in that Validator case its not required

2025-01-15 11:32 UTC, ericbrunner commented on Applications/AdminApi/src/AdminApi/appsettings.json
Done. BTW: Thats a local Rider setting, which was Indent: 2 on my machine. 
![image](https://github.com/user-attachments/assets/b42aba12-4522-4199-bebd-367cb7c67580)

2025-01-15 11:33 UTC, tnotheis commented on Modules/Tokens/src/Tokens.Application/Tokens/Queries/ListTokensByIdentity/Validator.cs
> in that Validator case its not required

Yeah, exactly. We usually only set it to `Cascade` when a following rule would throw an exception if the current one fails. For example, if there is a collection property, for which there are two rules:
* Not null
* Count > X

Then `Cascade` on the first rule would be necessary, because otherwise the second rule would throw a NullReferenceException because it tries to read `.Count` of `null`.

2025-01-15 11:36 UTC, ericbrunner commented on Applications/AdminApi/src/AdminApi/Extensions/IServiceCollectionExtensions.cs
> +                ""));
Done

2025-01-15 11:36 UTC, ericbrunner commented on Applications/AdminApi/src/AdminApi/Extensions/TokensServiceCollectionExtensions.cs
> +        services.AddTransient<ITokensRepository, TokensRepository>();
Done

2025-01-15 14:26 UTC, ericbrunner commented
> I know I told you it's not necessary to write an integration test for this functionality (because we can't create tokens via the Admin API), but I just thought about it, and I think we could at least add one like "Listing all tokens of an identity that doesn't have any tokens". This ensures that all DI wiring has been done correctly and that all dependencies can be resolved.

Check last commit

2025-01-16 09:33 UTC, tnotheis commented on Applications/AdminApi/src/AdminApi/Extensions/TokensServiceCollectionExtensions.cs
> +        services.AddTransient<ITokensRepository, TokensRepository>();
Sorry, I guess I wasn't clear. The `AddPersistence` method already exists in:

```
Modules/Tokens/src/Tokens.Infrastructure/Persistence/IServiceCollectionExtensions.cs
```

2025-01-16 09:37 UTC, tnotheis requested changes

2025-01-16 09:37 UTC, tnotheis commented on Applications/AdminApi/test/AdminApi.Tests.Integration/StepDefinitions/TokensStepDefinitions.cs
> +    private ApiResponse<ListTokensTestResponse> _tokensResult = null!;
You should be consistent with the naming. At least within one file.

You call it `_createIdentityResponse`, but `_tokensResult`, even though both are of type `ApiResponse<T>`

2025-01-16 09:37 UTC, tnotheis commented on Applications/AdminApi/test/AdminApi.Tests.Integration/StepDefinitions/TokensStepDefinitions.cs
> +    private ApiResponse<CreateIdentityResponse>? _createIdentityResponse;
Why do we need a field for that? As far as I can see, it's only used in one method.

2025-01-16 09:37 UTC, tnotheis commented on Applications/AdminApi/test/AdminApi.Tests.Integration/StepDefinitions/TokensStepDefinitions.cs
> +    private string _newIdentity = string.Empty;
```suggestion
    private string _newIdentityAddress = string.Empty;
```

2025-01-16 10:06 UTC, ericbrunner commented on Applications/AdminApi/src/AdminApi/Extensions/TokensServiceCollectionExtensions.cs
> +        services.AddTransient<ITokensRepository, TokensRepository>();
done

2025-01-17 07:54 UTC, tnotheis approved these changes

2025-01-17 08:36 UTC, merged